# This is a basic example blueprint for a Django web service and 
# the PostgreSQL database it connects to.
services:
  - type: web # A Python web service named django-app running on a free instance
    plan: starter
    name: my-node-app
    runtime: node
    repo: https://github.com/render-examples/express-hello-world.git
    buildCommand: "yarn"
    startCommand: "node app.js"
    disk:
      name: my-node-app-disk
      mountPath: /var/dataa
      sizeGB: 1
    envVars:
      - key: METAGAME_HOST_PORT
        fromService:
          name: metagame
          type: web
          property: hostport
      - key: METAGAME_HOST
        fromService:
          name: metagame
          type: web
          property: host
      - key: METAGAME_PORT
        fromService:
          name: metagame
          type: web
          property: port

