# This is a basic example blueprint for a Django web service and 
# the PostgreSQL database it connects to.
services:
  - type: web # A Python web service named django-app running on a free instance
    name: my-docusaurus
    runtime: static
    repo: https://github.com/StephenBarlow/docusaurus.git
    buildCommand: "yarn install; yarn build"
    staticPublishPath: ./build
    headers:
      - path: /blah
        name: X-Frame-Options
        value: oof
    routes:
      - type: redirect
        source: /old
        destination: /neww
