# Exported from Render on 2026-02-08T22:10:18Z
version: "1"
projects:
- name: Main Platform
  environments:
  - name: Production
    permissions:
      protection: enabled
    services:
    - type: web
      name: db-admin
      runtime: image
      image:
        url: docker.io/ankane/pghero:latest
      plan: free
      envVars:
      - key: WEB_CONCURRENCY
        sync: false
      - key: PGHERO_PASSWORD
        sync: false
      - key: PGHERO_USERNAME
        sync: false
      - key: DATABASE_URL
        sync: false
      region: oregon
      autoDeployTrigger: commit
    - type: web
      name: prod-web
      runtime: node
      repo: https://github.com/StephenBarlow/metagame
      plan: starter
      envVars:
      - key: BLAH
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        sync: false
      - key: NODE_VERSION
        sync: false
      region: oregon
      buildCommand: 'npm install '
      startCommand: npm start
      autoDeployTrigger: commit
      previews:
        generation: automatic
    - type: cron
      name: my-cron-job
      runtime: node
      repo: https://github.com/StephenBarlow/metagame
      plan: starter
      region: oregon
      buildCommand: npinstall
      startCommand: echo "hello"
      schedule: '*/3000 * * * *'
      autoDeployTrigger: commit
    databases:
    - name: prod-postgres
      databaseName: my_postgres_vm9t
      user: my_postgres_vm9t_user
      region: oregon
      ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
      postgresMajorVersion: "16"
